### ISSUE TITLE
Support installation of composer

### ISSUE THREAD

**Issue by sebastianheuer** [phar-io/phive#110]

**Comment by Ayesh** [comment]
FYI, Composer phars are signed using the keys: https://composer.github.io/pubkeys.html

**Comment by theseer** [comment]
Thanks for the reminder!

I've already looked at that page some time ago and still have no idea why one would consider embedding key information into an HTML document a good idea. Particularly when simply linking to a raw keyfile would made life so much easier for everybody?. Why do we now have to parse an HTML and extract that information? And it's not like that approach would be re-usable for other projects. It's a proprietary and cumbersome solution. 

I also fail to understand why the composer developers choose to use OpenSSL for signing rather than PGP - which is an established standard for package signing in the OS world with an equally established infrastructure around it to automate look-ups and key distribution.

With OpenSSL there is no independent infrastructure to publish and search for public keys. The PGP-Keyserver-System may not be perfect, but it beats parsing HTML to get the key for *one* project and implementing a different solution for the next.

To have support for installing composer with phive, we'd have to implement some additional custom things that are likely only relevant for composer. So, while I'd very much like to be able to install composer using phive, there are quite some things where the composer project decided to not follow established patterns. And I'm not yet convinced that phive is the correct place to "fix" that.

The main purpose of this issue is to track these potential custom requirements.

**Comment by amenk** [comment]
See also: https://github.com/composer/composer/issues/5155

**Comment by Seldaek** [comment]
I now published the keys as single addressable files, see https://composer.github.io/pubkeys.html for links. The reason it wasn't done is simply that nobody asked or needed it as the keys are bundled with the composer installer.

As for choosing openssl and not PGP, it's because that allows us to work exclusively with PHP in a fully cross platform way as we require the openssl extension to be installed anyway. PGP/GPG availability can hardly be relied upon, and I am not a fan of leaving users behind because of their OS choices.

If you can see some value in supporting openssl signatures, I think that'd be great as it would make phive work in more places, but if not I guess I'll have to look into publishing PGP signatures as well.

**Comment by amenk** [comment]
So on phive side we now would need a way to "trust" these OpenSSL signatures... maybe the URLs can just be referenced in the https://github.com/phar-io/phar.io/blob/master/data/repositories.xml and/or the phive.xml ?

**Comment by Seldaek** [comment]
As of https://github.com/composer/composer/releases/tag/2.0.3 composer releases on github will have a signature attached. I just tried to install it via phive and it works now without `--force-accept-unsigned` 👍 

Would be good if you can update the phar.io homepage to remove `--force-accept-unsigned` from the composer example. I also submitted https://github.com/phar-io/phar.io/pull/88 to add an alias.

**Comment by theseer** [comment]
PR is merged and live. I also updated the website to reflect the change.

**Comment by theseer** [comment]
Closing this issue as composer now comes with gpg signatures and even has an alias so is now fully supported.
