### ISSUE TITLE
Bad error message for missing signatures in GitHub releases

### ISSUE THREAD

**Issue by oqq** [phar-io/phive#117]
If I try to install the php-cs-fixer with
```bash
$ phive install FriendsOfPHP/PHP-CS-Fixer
```

I got the response
```
Phive 0.8.2 - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/friendsofphp/php-cs-fixer/releases
[ERROR]   No matching release found
```

Since there is of course a release with a phar file attached, i guess this error occurs if no signature is provided in releases.

Maybe the error message should be more particularly about this issue.

**Comment by theseer** [comment]
I understand the error message is not perfect. Technically though, it doesn't actually matter whether there is no release, no phar within any release or merely no signature: Phive cannot install it.

The question is, what is the expected behavior? Let's say you have 4 relesaes:
* One, merely a tag and not really a release yet (v4.0.0)
* Two, a release that does not include any additional attachments (v3.0.0)
* Three, a release with a phar but no signature file (v2.0.0)
* Four, a complete release with phar and signature (v1.0.0)

Currently, we'd automagically install Release 1.0.0 as that's the only one that is "sane" choice from the perspective of phive.

So, what shall we do? 
* Complain, that we cannot install the latest version since it's not an actual release?
* Complain, that we cannot 3.0.0 as it's not having the required attachments?
* Complain, that we cannot install 2.0.0 because of a lag of signature file?
* Silently install v1.0.0?
* Complain for all the cases and just install 1.0.0 anyhow?

**Comment by oqq** [comment]
Assumed we use composer reference, since i am using phive as tool replace for dev dependencies.

- If there is no issue on installing a dependency, composer just makes it happen without any message.
- If there is an issue, e.g. composer could not handle package conflicts, than all possible tags produces an error item with a detail why it is not possible to use that tag.

So how about to silently install any possible version, but throw out an error message if not suitable release was found?

```bash
$ phive install vendor/package
[ERROR] Phive could not find any suitable release
vendor/package[v2.0.1] (no signature)
vendor/package[v2.0.0, v1.1.0] (no phar)
```

```bash
$ phive install vendor/package:^1.0.0
[ERROR] Phive could not find any suitable release
vendor/package[v1.1.0] (no phar)
```

**Comment by theseer** [comment]
After spending some more time thinking about it, I still like that approach and will hopefully have time soon to implement it.
