### ISSUE TITLE
Option to specify PHP binary

### ISSUE THREAD

**Issue by kanevbg** [phar-io/phive#129]
I have not found such. In environments with more than one version it is a must.

**Comment by belanur** [comment]
Since the `phive` executable is a PHP script itself, you could run phive with a specific php binary by just running that binary with the phive script as an argument, e.g. `/usr/bin/php72 /path/to/phive-installation/phive version`. This could also be wrapped in a bash script symlinked to `/usr/bin/` for convenience.

**Comment by theseer** [comment]
I'm not sure what the implied issue is?

As of now, `phive` works on PHP 5.6 or higher.  While that will change to be 7.1+ by the end of the year when everything before 7.1 is EOL, the version used is actually quite unimportant.

Except of course, if a manifest is in use that requires a certain PHP Version for its phar. But that again is not an issue with phive?

What's the intend of this issue?

**Comment by kanevbg** [comment]
I have just forgot what was the issue, I had to be more specific. I guess that the system was using in some cases the default PHP binary in a way, can't think of anything else at this time :/

**Comment by theseer** [comment]
Okay, if you remember it, feel free to post another comment.

Until then, I'll close this.
