### ISSUE TITLE
"--copy" does not work on Windows

### ISSUE THREAD

**Issue by ThomasWeinert** [phar-io/phive#140]
"-c/--copy" copies the Phar into the tools directory, but without the file extension. The tools can not be called directly that way - only with "php tools\toolname". The BatPharActivator should be called to create a matching batch file.

Why is the copy flag stored in the phive.xml? It feels more like an environment specific option to me.

**Comment by theseer** [comment]
That indeed sounds like a bug. I though on windows we always do a copy because windows can't do symlinks properly. But then, I don't use windows.

The flag is stored because it is a decision done on behalf of project: Quite some people commit the binary of the tools along in their repository - which of course will only work when there is a copy rather than a symlink. And for updates we also want to maintain that state. I prefer to have that in a clean config file rather than having to guess from a file that many or may not exist.

**Comment by ThomasWeinert** [comment]
That way copy as a package/project flag makes sense. I misunderstood it. Thanks for the explanation.

**Comment by theseer** [comment]
Is this issue still relevant, given #141 has been merged?

**Comment by ThomasWeinert** [comment]
Yes. The activator is not triggered if the flag is set.
