### ISSUE TITLE
Travis fails to execute mv phive.phar $HOME/.phive

### ISSUE THREAD

**Issue by Aerendir** [phar-io/phive#159]
I'm trying to use the `.travis.yml` configuration used in the repository of `Phive` itself to configure mine, but Travis fails to execute [this command](https://github.com/phar-io/phive/blob/master/.travis.yml#L9):

```yaml
before_install:
    ...
    - if [ ! -f $HOME/.phive/phive.phar ]; then ant getphive ; mv phive.phar $HOME/.phive ; fi
```

[The error I receive](https://travis-ci.org/Aerendir/aws-ses-monitor-bundle/jobs/401268291) is this:

```console
...
0.00s$ if [ ! -d $HOME/.phive ]; then mkdir $HOME/.phive ; fi
0.66s$ if [ ! -f $HOME/.phive/phive.phar ]; then ant getphive ; mv phive.phar $HOME/.phive ; fi
Buildfile: build.xml does not exist!
Build failed
mv: cannot stat ‘phive.phar’: No such file or directory
The command "if [ ! -f $HOME/.phive/phive.phar ]; then ant getphive ; mv phive.phar $HOME/.phive ; fi" failed and exited with 1 during .
Your build has been stopped.
```

Maybe this issue is not striclty related to `Phive` itself, but I will appreciate a lot any help to configure Travis to use `Phive` to download my required dependencies without the needing of adding them to `composer.json`.

**Comment by theseer** [comment]
The lines in our `.travis.yml` are a temporary hack since `https://phar.phpunit.de` requires TLSv1.2 which Travis does not seem to support on old(er) versions of PHP and thus Phive cannot download the `phpunit.par`. 

We use `ant` for our build automation. Thus, instead of writing every build step into a proprietary Travis only format, we have the actual work happening in `ant` and its `build.xml`.

Your project does not seem to use `ant` and thus our solution does not work for you.
