### ISSUE TITLE
Signing key contains example.org email address

### ISSUE THREAD

**Issue by russellvt** [phar-io/phive#168]
It's largely cosmetic, but probably not the best idea to have an "example.org" signing key...

````
russell@hostname:~/bin$ gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
gpg: requesting key 9B2D5D79 from hkp server hkps.pool.sks-keyservers.net
gpg: key 9B2D5D79: public key "phar.io <team@phar.io>" imported
gpg: key 9B2D5D79: public key "Totally Legit Signing Key <mallory@example.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 2  (RSA: 2)
````

**Comment by theseer** [comment]
Those are two different keys, sharing - as it seems - the same short id.

Short IDs are bound to have easy duplicates which is why their use is discouraged and considered deprecated.

Phar.io and Phive do not advocate the use of the short id and Phive doesn't do so internally either.  In fact, even the documentation on how to [Install](https://phar.io/#Install) uses the long Id.

We for some reason still had the short ID mentioned in our webpage's footer.
That is obviously at least confusing and got fixed.
