### ISSUE TITLE
Allow custom filenames for GPG signature

### ISSUE THREAD

**Issue by belanur** [phar-io/phive#21]
Currently the filename of the GPG signature file for a phar is composed by using the filename of the phar and adding `.asc`. The phar.io repository URL allows providing a custom filename for the signature file and Phive should act accordingly.

**Comment by theseer** [comment]
Status Update:

Since commit b3bae81d2c94ef67c015c6bacf7fdb0787f4e2e2 we have the following:

- The phar.io repository resolver honors an url attribute in the repository xml,
- The github releases repository resolver detects .asc and .sig files within the assets
- The url resolver still appends .asc to the phar url

**Comment by theseer** [comment]
The current implementation was determined to be good enough.

We consider installing via a full URL or using a non-standard name for the signature files an edge case.
So for now, there is no further development planned on this.

**Note**: If you stumbled upon this issue using a search and can make a valid case where the currently missing functionality would be required, please open a new, specific ticket for that and we might reconsider.
