### ISSUE TITLE
Is it possible to use reference (for example) the TestCase class in phpunit?

### ISSUE THREAD

**Issue by ShawnMcCool** [phar-io/phive#268]
I understand that the phpunit.phar binary can be used to run tests. But how would I go about extending the TestCase class to create my own tests?

**Comment by theseer** [comment]
I'm not sure how this is in any way related to `phive`, as a tool that provides one of many ways to install PHPUnit?

If you want to learn on how to write tests with PHPUnit, read up in the documentation: For PHPUnit 9, for instance https://phpunit.de/getting-started/phpunit-9.html

**Comment by halloei** [comment]
I'm currently testing PHIVE and I'm wondering how to use it with PHPUnit, too. [This](https://github.com/phar-io/phive/issues/160) issue might be related.

The goal is to remove PHPUnit from the project's Composer dev-dependencies. Doing so removes all of PHPUnit's resources (i.e. `PHPUnit\Framework\TestCase` class), of course. How are we supposed to write tests now? The IDE will complain about missing classes and features like autocomplete won't work anymore.
PHIVE seems great for tools like Codesniffer. But as it is advertised in combination with PHPUnit, there must be a solution I don't know of yet. Otherwise I see no use of PHIVE when it's about PHPUnit.

@theseer Could you please explain this to us?

**Comment by theseer** [comment]
The phar Archive of PHPUnit contains all the Code required to run tests, and thus also contains all the Code required to provide autocomplete support within an IDE.

I'm assuming you use PHPStorm as an IDE, because they - for whatever reason - do not index phar archives *unless their file name ends on .phar*. So, the answer to this issue comes in four parts:

- It's not phive's fault that the IDE is not detecting the fact it's a phar archive even if the file name doesn't end on `.phar`, thus doesn't index it - but of course that's annoying
- On the other hand, PHPUnit indeed is a special case and the phar archive used to run the tests should not even be indexed because it contains lots of code that is *not* to be autocompleted - unless you develop PHPUnit itself.
- PHPUnit is lacking a "stub" phar, that only contains the signatures needed for automcompletion. This is on the backlog for future PHPUnit versions and will also need an update of phive to support that properly.
- A simple fix is to either explicitly tell phive you want to install PHPUnit as `phpunit.phar` - for that you have to change the `location` attribute in the `phive.xml` / `.phive/phars.xml` file. Or, if you want to have both, create a symlink (`ln -s tools/phpunit tools/phpunit.phar`).

**Comment by theseer** [comment]
That sounds more like a PHPUnit related issue - when installed as phar - rather than phive specific problem.
I personally don't use PHPStan so I don't have about zero experience with it. But let's see. Some wild guessing to come ;)

- The link you provided shows two ways to add content from phars to whatever PHPStan is doing with these files. 

- The actual filename doesn't seem to matter but it needs to find the directory or a bootstrap/autoloader script within the phar. PHPUnit's phar doesn't have a "bootstrap" file but uses the manifest stub to create and register its autoloader. I haven't tried that, but maybe `phar:///path/to/phpunit.phar` as a `bootstrapFiles`-entry already works. Technically it might as the autoloader should be registerted that way.

If that doesn't work, the "scan" approach mentioned by the OP in the issue you referenced might. But given PHPUnit's phar doesn't have a "src" directory in there, the exact approach won't. I'm not sure what you're trying to add and for what reason, but `phar:///path/to/phpunit.phar/phpunit` will get you the directory of PHPUnit itself within the phar.

Hope that helps.

**Comment by halloei** [comment]
The solution for this is simply to remove the `phar://` prefix from the file path:
```
bootstrapFiles:
	- tools/phpunit.phar
```

Thank you for taking a look into this, too!
