### ISSUE TITLE
provide sha1 signed phar

### ISSUE THREAD

**Issue by glensc** [phar-io/phive#30]
please consider providing sha1 signed phar to avoid such errors:

```
[/tmp] ➔ phive.phar 
PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/home/glen/Dropbox/bin/phive.phar" has a unsupported signature' in /home/glen/Dropbox/bin/phive.phar:102
Stack trace:
#0 /home/glen/Dropbox/bin/phive.phar(102): Phar::mapPhar('phive.phar')
#1 {main}
  thrown in /home/glen/Dropbox/bin/phive.phar on line 102
```

please see if you can also build more compatible phar file:
https://github.com/sebastianbergmann/phpunit/issues/1948#issuecomment-155438262
https://github.com/sebastianbergmann/phpunit/issues/1948#issuecomment-155437695
https://github.com/sebastianbergmann/phpunit/commit/4ef58ab03115c22c05ad05a33d0fee5986a2b208

**Comment by theseer** [comment]
I'm not convinced that is a good idea. While we technically of course could provide a sha1 version of the next milestone release this won't solve the underlying issue for the phars phive is attempting to install. We thus would have to bail out in case we run into the missing support. Not exactly a nice solution.

To me the problem is actually in the PHP build shipping with PLD and potentially derivatives as all other tested distributions seem to compile PHP in a way that SHA256/SHA512 are available. While I do agree the compile time decision is broken and should be considered a bug within PHP itself, the build provided by PLD is the problem and should get adjusted.

**Comment by theseer** [comment]
Not to mention that falling back to outdated hashing algorithms is not exactly a favorable solution to begin with.
