### ISSUE TITLE
Discussion: keys.openpgp.org was down for two hours, which affected CI pipelines using phive to install phars

### ISSUE THREAD

**Issue by ArtemGoutsoul** [phar-io/phive#300]
keys.openpgp.org was down for about two hours on Dec 17, 2020. This caused CI pipelines using phive to install packages that had their keys in keys.openpgp.org to fail. Which for some teams could prevent merges and releases.

Any ideas how to handle such situations? At least to be less disrupted by intermittent downtimes.

We use phive to install psalm, phan, phpstan and phpcs in a docker-compose environment.

Our handling of the situation:
- we temporarily modified our docker-compose entrypoint to install phars using curl and commented out phive install
- we will now revert the hack

Other possible options:
- install keys into docker image for CI (is it a good idea?)
- cache phar installation folder between builds (can be tricky in some environments)
- include installation folder into docker image, this way it would at least have some default versions of phars, that would be updated according phive.xml, this would require occasional updates of the docker image, which could be a sensible compromise

**Comment by theseer** [comment]
Welcome to the world of cloud computing ;-)

I'm not sure if there is anything `phive` can do by itself here, as we of course depend on various services to be available: keyservers, github, gitlab, ....

To address the very problem this issue is about: Phive does need the public key to verify signatures. This of course does not have to be downloaded at phive runtime but can be in the GPG key ring already - as it would be for 2nd+ installs.

My recommendation thus would be to merely store (cache) the gpg key ring. Whether or not that is within a container or uses other caching means probably depends on your workflow. 

Phive also keeps downloaded phars - by default in `~/.phive/phars` (can be changed by `--home` or setting `PHIVE_HOME`). That's different from the projects `./tools` directory.

I don't see any issues in caching `~/.phive`. Unless a dependency changed, with this cached, phive should be able to fully operate "offline".

**Comment by ArtemGoutsoul** [comment]
Yeah :) understandable, with cloud services we get things done faster, but introduce some potentially unstable dependencies

Thanks for your thoughts and clarifications!
