### ISSUE TITLE
Requiring pre 1.0 packages

### ISSUE THREAD

**Issue by vertexvaar** [phar-io/phive#310]
### Actual behavior:
```shell
app@91d844df2b6f:/app$ phive install grumphp:^0.19.0 
Phive 0.14.5 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://github.com/phpro/grumphp/releases/download/v0.22.0/grumphp.phar
Downloading https://github.com/phpro/grumphp/releases/download/v0.22.0/grumphp.phar.asc
```
### Expected behavior:
```shell
app@91d844df2b6f:/app$ phive install grumphp:^0.19.0 
Phive 0.14.5 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://github.com/phpro/grumphp/releases/download/v0.19.1/grumphp.phar
Downloading https://github.com/phpro/grumphp/releases/download/v0.19.1/grumphp.phar.asc
```

Notice that `phive` should install `v0.19.1` instead of `v0.22.0`

### Reason
I first stumbled over this behavior when using composer. Composer strictly sticks to semVer and will not install a higher minor level when the package did not yet have its first release. See https://getcomposer.org/doc/articles/versions.md#caret-version-range-
The actual section in semver is here: https://semver.org/#spec-item-4

I think phive should adapt this behavior to a) strictly follow semver, b) install packages by the same rules as composer

**Comment by theseer** [comment]
Constraint handling or definition is not part of the semver specification: Semver, aka semantic versioning, only defines the rules on when and how to update which fragment of the version identifier and how they should compare (e.g. alpha being less than x.0.0). There are no constraints defined in semver, as far as I can tell.

So technically speaking, as `0.22.0` is greater than `0.19.1`, the behavior of phive is correct and "semver compliant", given the result of the comparison follows the semver rules.

On the other hand: I do see the point in composer's behavior to pin `^` to the minor version rather than to the major version.

Certainly worth considering.

**Comment by theseer** [comment]
As of phar-io/version 3.1.0, the desired behavior has been implemented.

Phive 0.15.0 ships with phar-io/version 3.1.0.
