### ISSUE TITLE
phar.io Install script broken

### ISSUE THREAD

**Issue by nvuillam** [phar-io/phive#321]
It seems that since 0.15.0 release, the installation script does not work anymore.

Reason seems to be that `wget -O phive.phar https://phar.io/releases/phive.phar` now returns a 404 error

Below the error from my [Dockerfile](https://github.com/nvuillam/mega-linter/blob/51e43d64a99960accec79033f952ee886e2651b8/Dockerfile#L243) execution

```shell
Step 36/97 : RUN wget --tries=5 -q -O phive.phar https://phar.io/releases/phive.phar     && wget --tries=5 -q -O phive.phar.asc https://phar.io/releases/phive.phar.asc     && PHAR_KEY_ID="0x9D8A98B29B2D5D79"     && ( gpg --keyserver keyserver.pgp.com --recv-keys "$PHAR_KEY_ID"         || gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$PHAR_KEY_ID"         || gpg --keyserver pgp.mit.edu --recv-keys "$PHAR_KEY_ID"         || gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "$PHAR_KEY_ID" )     && gpg --verify phive.phar.asc phive.phar     && chmod +x phive.phar     && mv phive.phar /usr/local/bin/phive     && rm phive.phar.asc
 ---> Running in 7b235479a1f1
wget: server returned error: HTTP/1.1 404 Not Found
```

It blocks new releases of [Mega-Linter](https://nvuillam.github.io/mega-linter/), please could you fix the issue or provide a workaround ?

Thanks :)

**Comment by heiglandreas** [comment]
It also breaks CI pipelines on github using 

```yaml
uses: "shivammathur/setup-php@v2"
with:
    tools: "phive"
```

with the message

```
==> Setup Tools
✓ composer Added composer 2.1.5
chmod: cannot access '/usr/local/bin/phive': No such file or directory
✗ phive Could not setup phive
```

**Comment by theseer** [comment]
Debugging this...

**Comment by theseer** [comment]
Apparently, even `nginx` sometimes is just wind^h in need of a restart...

**Comment by heiglandreas** [comment]
Can confirm! It works again! Thank you for the fast resolution!

**Comment by theseer** [comment]
## Post mortem ##

### Reason of failure
Digging a bit deeper into log files, it appears to have been a DNS issue.


### Details

The release redirect is powered by a small (hacky? ;) ) [PHP script](https://github.com/phar-io/phar.io/blob/master/php/release.php) which connects to the github API to find the latest release and redirect to the appropriate asset.

Based on the logs from PHP, it appears to have failed to contact github and thus didn't have the required data to perform the redirect. For debugging purposes, i ran that script on the CLI, which took way longer than it should have before finally failing, pointing at connection issues.

When trying to manually connect to github, the hostname could not be resolved. I rebooted the VM, which, apart from of course restarting the processes in question (nginx, php-fpm), also updated the network configuration - namely the  DNS server to use. After that, all seems to be working fine again.

### Actions taken

Performing an API call to github.com upon every request is a hack, particularly since the current release information doesn't change very often.

The links to the asset files associated with a release are static. The best fix would be to create the redirects statically upon release. I'll create an issue to change this.

**Comment by nvuillam** [comment]
Works for Mega-Linter now too, thanks for your reactivity :)

**Comment by theseer** [comment]
You're welcome.

And, just for the record: It had nothing to do with the 0.15.0 release ;)
