### ISSUE TITLE
Integrate into Composer

### ISSUE THREAD

**Issue by webmozart** [phar-io/phive#34]
Hi :) Why do you run Phive as a separate project from Composer? I think this functionality would be highly useful for any Composer user! Also, integrating it there would allow you to reuse a lot of existing infrastructure.

See composer/composer#4381

**Comment by belanur** [comment]
Hello! :)

This seems to be related to #12 - we definitely want to look at providing a composer plugin that might bring this kind of functionality. 

I am not convinced that integrating PHAR management directly into composer would be a better way though, as the complexity of handling both use cases (i.e. managing libraries that are used within a project's code against managing a set of binaries as part of a project's toolchain) in one single tool might just be too (damn) high.

Maybe @theseer would like to elaborate on this as well :)

**Comment by theseer** [comment]
I wholeheartedly agree to what @belanur already wrote.

And as @seldaek mentioned in his [comment](https://github.com/composer/composer/issues/4381#issuecomment-211989933) regarding the referenced composer issue [4381](composer/composer#4381), this probably should be covered by a plugin.

Since we already do have a tracking issue for that (issue #12), I'll close this ticket.
