### ISSUE TITLE
certificate expired on phive install

### ISSUE THREAD

**Issue by itsmoikala** [phar-io/phive#367]
Hello,

I look upon (https://phar.io/#Install)

> gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79

returns 

> gpg: keyserver receive failed: Certificate expired

I need help with this

**Comment by theseer** [comment]
That either was a temporary issue with the `keys.openpgp.org` keyserver or is a problem in your network setup.

The error you quoted (`Certificate expired`) hints at an outdated server certificate (since we recommend using `hkps` the connection has to be TLS encrypted). It has nothing to do with our keys. Given I cannot reproduce that on my system, I consider that a non-issue on our side:

```
theseer@nyda /tmp/x6 $ GNUPGHOME=/tmp/x6 gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79
gpg: keybox '/tmp/x6/pubring.kbx' created
gpg: /tmp/x6/trustdb.gpg: trustdb created
gpg: key 9D8A98B29B2D5D79: public key "phar.io <team@phar.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
****
```

Just try again and if the problem persists talk to your network administrator to check what's going on. There is really nothing we can do here, I'm afraid.
