### ISSUE TITLE
Issue with installing phing

### ISSUE THREAD

**Issue by piotr-zuralski** [phar-io/phive#91]
`phive install phing`
```
Phive 0.6.2 - Copyright (C) 2015-2016 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    Could not resolve requested PHAR phing
```

`phive install https://www.phing.info/get/phing-latest.phar`
```
[ERROR]    Could not extract PHAR version from https://www.phing.info/get/phing-latest.phar
```

related with #90 
`phive install phingofficial/phing`
```
Downloading https://api.github.com/repos/phingofficial/phing/releases
Downloading https://github.com/phingofficial/phing/releases/download/2.15.0/phing-2.15.0.phar
Downloading https://github.com/phingofficial/phing/releases/download/2.15.0/phing-2.15.0.phar.asc
[ERROR]    Could not download from https://github.com/phingofficial/phing/releases/download/2.15.0/phing-2.15.0.phar.asc: The requested URL returned error: 404 Not Found (while requesting https://github.com/phingofficial/phing/releases/download/2.15.0/phing-2.15.0.phar.asc)
```

`phive install https://www.phing.info/get/phing-2.15.0.phar`
```
Phive 0.6.2 - Copyright (C) 2015-2016 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://www.phing.info/get/phing-2.15.0.phar
Downloading https://www.phing.info/get/phing-2.15.0.phar.asc
[ERROR]    Could not download from https://www.phing.info/get/phing-2.15.0.phar.asc: The requested URL returned error: 404 Not Found (while requesting https://www.phing.info/get/phing-2.15.0.phar.asc)
```

**Comment by theseer** [comment]
Thank you for your report.  Let me address the individual results:

 ```phive install phing```
As there is no registered alias (as of yet), this can't work. When the signature issue is resolved, we might consider adding one.

 ```phive install https://www.phing.info/get/phing-latest.phar```
Since the phar file does not contain a [manifest](https://github.com/phar-io/manifest) and the file name does not contain a version identifier, the 2nd approach also fails. This is a won't fix.

 ```phive install phingofficial/phing ```
 ```phive install https://www.phing.info/get/phing-2.15.0.phar ```

These approaches fail because the phing developers do not sign their releases using gpg/pgp.
For security reasons, phive requires a gpg signature to be published alongside the phar.

Until the phing developers release their phars with a valid signature and have published the gpg key used for signing, there is nothing we can do.

**Comment by piotr-zuralski** [comment]
Ok, thanks for pointing things out
