### ISSUE TITLE
PublicKey not found on key servers

### ISSUE THREAD

**Issue by jpuck** [phar-io/phive#97]
Hi, I've got a noobie question that I probably missed in the docs:

How do I submit my public key to a valid registry?

I've created [this project release][1], followed [these instructions][2] to generate a new gpg key, followed [these instructions][3] to create the signature under the naming convention, and uploaded it to the release.

Now when I run:

    phive install jpuck/carbon-console

I get this error:

> ```
> Phive 0.6.3 - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
> Downloading https://api.github.com/repos/jpuck/carbon-console/releases
> Downloading https://github.com/jpuck/carbon-console/releases/download/1.0.0/carbon-console.phar
> Downloading https://github.com/jpuck/carbon-console/releases/download/1.0.0/carbon-console.phar.asc
> Downloading key 480E381960C427CB
> Trying https://hkps.pool.sks-keyservers.net
> Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x480E381960C427CB&op=index&options=mr
> [WARNING]  Failed with error code 22: The requested URL returned error: 404 Requested URL not found (while requesting https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x480E381960C427CB&op=index&options=mr) 
> [ERROR]    PublicKey 480E381960C427CB not found on key servers 
> ```
> 

I tried exploring around https://hkps.pool.sks-keyservers.net/ despite their SSL certificate error and found the submission form. But as I'm completely new to gpg, I wasn't sure what the `ASCII-armored version` would be exactly. And it seemed strange that anyone could freely submit without authentication (wouldn't that defeat the purpose of a trust chain?), so I was hoping to reach out to you for guidance. How should I proceed?

Thanks!

[1]:https://github.com/jpuck/carbon-console/releases
[2]:https://phar.io/howto/generate-gpg-key.html
[3]:https://phar.io/howto/sign-and-upload-to-github.html

**Comment by theseer** [comment]
Thanks for supporting phive with your project and for pointing out that we need to further enhance our documentation on this subject.

So let's have a look at your points/questions:

- The host ```hkps.pool.sks-keyservers.net``` is used for key lookups and not actually a single host but a pool of servers. They use a custom CA which causes regular browsers to show certificate warnings. Feel free to read up on the [pool defintions here](https://sks-keyservers.net/overview-of-pools.php) for details.

- For human interaction they have a [regular website](https://sks-keyservers.net/i/). It should work without the certificate warning.

- ASCII-armored is the technically complex way of saying you should uploaded a plain text representation of the public key that normally would be binary. GnuPG calls this "ascii armored" when exporting it. You can find more details [on key exporting here](https://www.gnupg.org/gph/en/manual/x56.html#AEN64).

- Regarding the trust chain: Yes and no. Of course anybody can create a gpg key for any address and upload it to a public key server. So, in theory, that means I could claim to be you and there is nothing you can do about it. But that's not really a problem for two reasons:

  - A single key is not exactly a *chain*. Other people or organizations, potentially someone you trust, need to sign your key with theirs, increasing the level of trustworthiness and forming the actual chain. It's actually the same as with TLS certificates where a CA like letsencrypt signs your key and your browser trusts letsencrypt and because of that your key/certificate is also accepted

  - The idea of the keyserver is _not_ to make any claims about the authenticity. It merely provides an automated means to get a public key based on it's ID. It's up to the user to decide whether the result is to be trusted, as in whether or not to import the pubic key to the local chain. You can of course also manually add a public key you received by other means. Linux distributions for example do that by providing their keys in release-packages or the base OS installation image.

So your next step would indeed be to export your *public* key (in ascii armored format) and submit it using the interactive page to the sks keyservers.

**Comment by jpuck** [comment]
@theseer thanks so much for the information, that's exactly what I needed!

One note I would suggest for your documentation in addition to your thorough response is to wait about 15 minutes for the key to propagate (for impatient people like myself). I found that even though my public key showed up in keyserver search results instantly after submission, it still took about 15 minutes before phive recognized it and was able to successfully download the key.

Feel free to close this ticket whenever you want.

**Comment by theseer** [comment]
Documentation has been updated.
